# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rspec-rr}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Joseph Wilk"]
  s.date = %q{2010-12-06}
  s.description = %q{Helping Rspec and Rspec-rails play nicely with RR the test double framework.}
  s.email = %q{joe@josephwilk.net}
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    "MIT-LICENSE",
    "README.textile",
    "Rakefile",
    "TODO.txt",
    "VERSION.yml",
    "generators/rspec_default_values.rb",
    "generators/rspec_rr_scaffold/rspec_rr_scaffold_generator.rb",
    "generators/rspec_rr_scaffold/templates/controller_spec.rb",
    "init.rb",
    "install.rb",
    "lib/rspec/rr.rb",
    "lib/rspec/rr/mocks.rb",
    "spec/rspec/rr/ar_classes.rb",
    "spec/rspec/rr/mocks_spec.rb",
    "spec/rspec/rr/null_object_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "tasks/rspec_rr_tasks.rake",
    "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/josephwilk/rspec-rr}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Helping Rspec and Rspec-rails play nicely with RR the test double framework}
  s.test_files = [
    "spec/rspec/rr/ar_classes.rb",
    "spec/rspec/rr/mocks_spec.rb",
    "spec/rspec/rr/null_object_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

